apiVersion: apps/v1
kind: Deployment
metadata:
  name: turbo-test
  namespace: turbo-test
spec:
  replicas: 2
  selector:
    matchLabels:
      app: turbo-test
  template:
    metadata:
      labels:
        app: turbo-test
    spec:
      containers:
      - name: turbo-test
        image: rahuldocker2/turbo-test:a95e6522e81f859e7ac631f958fe5273f2518c10
        ports:
        - containerPort: 80
