apiVersion: v1
kind: Service
metadata:
  name: turbo-test-service
  namespace: turbo-test
spec:
  type: LoadBalancer
  selector:
    app: turbo-test
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
