name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: rahuldocker2/turbo-test:${{ github.sha }},rahuldocker2/turbo-test:latest

      - name: Update Kubernetes Manifests
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          sed -i "s|rahuldocker2/turbo-test:.*|rahuldocker2/turbo-test:${{ github.sha }}|" k8s/deployment.yaml
          git add k8s/deployment.yaml
          git commit -m "Update image to rahuldocker2/turbo-test:${{ github.sha }}"
          git push
